// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwarmRoute.TrafficControl.Infra.Data.Context;

#nullable disable

namespace SwarmRoute.TrafficControl.Infra.Data.Migrations
{
    [DbContext(typeof(TrafficControlDbContext))]
    partial class TrafficControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwarmRoute.TrafficControl.Infra.Data.Entities.ReservationAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaseCount")
                        .HasColumnType("integer");

                    b.Property<string>("LeasesJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ReservationTableId")
                        .HasColumnType("uuid");

                    b.Property<long>("StateVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_ReservationAudits_CreatedAtUtc");

                    b.HasIndex("ReservationTableId")
                        .HasDatabaseName("IX_ReservationAudits_ReservationTableId");

                    b.ToTable("ReservationAudits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
