// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwarmRoute.Map.Infra.Data.Context;

#nullable disable

namespace SwarmRoute.Map.Infra.Data.Migrations
{
    [DbContext(typeof(MapDbContext))]
    partial class MapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwarmRoute.Map.Domain.Aggregates.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("StateChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StateChangedAtUtc");

                    b.Property<long>("StateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roadmaps_Name");

                    b.ToTable("Roadmaps", (string)null);
                });

            modelBuilder.Entity("SwarmRoute.Map.Domain.Aggregates.Roadmap", b =>
                {
                    b.OwnsMany("SwarmRoute.Map.Domain.Entities.MapBlock", "Blocks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlockId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("ContainedLineIds")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("ContainedLineIds");

                            b1.Property<string>("ContainedSiteIds")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("ContainedSiteIds");

                            b1.Property<string>("MaxPos")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("MaxPos");

                            b1.Property<string>("MinPos")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("MinPos");

                            b1.Property<Guid>("RoadmapId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RoadmapId", "BlockId")
                                .IsUnique()
                                .HasDatabaseName("IX_RoadmapBlocks_RoadmapId_BlockId");

                            b1.ToTable("RoadmapBlocks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoadmapId");
                        });

                    b.OwnsMany("SwarmRoute.Map.Domain.Entities.MapLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ControlPos1")
                                .HasColumnType("jsonb")
                                .HasColumnName("ControlPos1");

                            b1.Property<string>("ControlPos2")
                                .HasColumnType("jsonb")
                                .HasColumnName("ControlPos2");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision");

                            b1.Property<string>("EndStationId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("InterferenceLineIds")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("InterferenceLineIds");

                            b1.Property<string>("InterferenceSiteIds")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("InterferenceSiteIds");

                            b1.Property<string>("LineId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("LineType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("RoadmapId")
                                .HasColumnType("uuid");

                            b1.Property<string>("StartStationId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.HasKey("Id");

                            b1.HasIndex("RoadmapId", "LineId")
                                .IsUnique()
                                .HasDatabaseName("IX_RoadmapLines_RoadmapId_LineId");

                            b1.ToTable("RoadmapLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoadmapId");
                        });

                    b.OwnsMany("SwarmRoute.Map.Domain.Entities.MapSite", "Sites", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Enable")
                                .HasColumnType("boolean");

                            b1.Property<string>("InterferenceLineIds")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("InterferenceLineIds");

                            b1.Property<string>("InterferenceSiteIds")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("InterferenceSiteIds");

                            b1.Property<string>("Pos")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Pos");

                            b1.Property<Guid>("RoadmapId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SiteId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("SiteType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("RoadmapId", "SiteId")
                                .IsUnique()
                                .HasDatabaseName("IX_RoadmapSites_RoadmapId_SiteId");

                            b1.ToTable("RoadmapSites", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoadmapId");
                        });

                    b.Navigation("Blocks");

                    b.Navigation("Lines");

                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
